### PR TITLE
[2.x] Require an actual login

### PR DESCRIPTION
**Pull request by Jade-GG**
see: https://github.com/rapidez/core/pull/613

### CODE REVIEW

**Review by Roene-JustBetter — DISMISSED** [review]

**Review by jordythevulder — APPROVED** [review]

**Comment by royduin** [comment]
Is this for v2 or v3?

**Comment by Jade-GG** [comment]
> Is this for v2 or v3?

This was for v2, I'll update the branch and check if v3 also needs it in a moment :)

**Comment by royduin** [comment]
Any info?

**Comment by Jade-GG** [comment]
> Any info?

Copied from the PR mentioned at the start:

"Previously, you could just type in any random password in the password box and it would validate without the need to log in, allowing people to actually try placing an order on an existing account without logging in. This fixes that bug."

**Comment by royduin** [comment]
And why do we need a checkbox for that? How does it work and look?

**Comment by Jade-GG** [comment]
> And why do we need a checkbox for that? How does it work and look?

Right, I'll elaborate on that:

As long as the password field is visible, the form should never validate (note, in v3 this can mean you're creating an account so there's a v-if on it to check that there). We can't (really) do this with just the textbox itself, we can only make the textbox required which isn't enough.

So, the simplest solution is that we can add an invisible checkbox that can never be checked, give it a custom validation message, and then give it the bounding box of the password field so that the validation message looks like it's just coming from the password field.

**Comment by royduin** [comment]
Ah nice! Thanks for the info 🚀

**Pull request merged**
